### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password"
}

### signin a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password"
}

### signout a user
POST http://localhost:3000/auth/signout


### Find a particular user with given ID
GET http://localhost:3000/auth/2

### get currently signed in user
GET http://localhost:3000/auth/whoami

### Find all users with given email
GET http://localhost:3000/auth?email=test@example.com

### Remove a particular user with given ID
DELETE http://localhost:3000/auth/6

### Update a particular user with given ID
POST http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "updated password"
}